import Provider from "@/components/Provider";
import "./globals.css";
import { Inter } from "next/font/google";
import SigninButton from "@/components/SigninButton";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Minimal Strokes",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full text-sm sm:text-base md:text-lg lg:text-xl xl:text-xl`}
      >
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
